png(filename = "Plot4.png",width = 480,height = 480,units = 'px')
par(mfcol=c(2,2))
plot(y$newdate,as.numeric((as.character(y$Global_active_power))),type = "l",ylab = "Global active power(kilowatt)",xlab ="")
plot(y$newdate,as.numeric(as.character(y$Sub_metering_1)),type="l",yaxt='n',ylab= "Energy sub metering",xlab="")
lines(y$newdate,as.numeric(as.character(y$Sub_metering_2)),col = "red")
lines(y$newdate,as.numeric(as.character(y$Sub_metering_3)),col = "blue")
axis(side = 2,at=seq(0,30,by=10))
legend("topright",legend=c("sub_metering_1","sub_metering_2","sub_metering_3"),col = c("black","red","blue"),lty = c(1) ,bty ="n")
plot(y$newdate,as.numeric(as.character(y$Voltage)),xlab="datetime",ylab="Voltage",type = 'l')
plot(y$newdate,as.numeric(as.character(y$Global_reactive_power)),type = 'l',yaxt ='n',xlab="datetime",ylab="Global_reactive_power")
axis(side =2,at=seq(0,0.5,by=0.1))
dev.off()